### ISSUE TITLE
Dead Simple Sensor -- Outdoor Temp vs. Indoor Temp

### ISSUE THREAD

**Issue by bryanbr23** [bryanbr23/-home-assistant-config#8]
**Objective**
Make it super simple for my family to know if they open the windows or close the windows to control temperature. 
We have no Air-Conditioning, so opening the windows in evening helps keep temperatures low.  So, let's create sensors to do that. 

**Ingredients**
Nothing fancy yet, just HA Sensors.

**Implementation**
```
# This Sensor is dead simple text if warmer or cooler outside
platform: template
sensors:
  warmer_or_cooler_outside:
    friendly_name: 'Warmer or Cooler Outside'
    value_template: >
      {%- if states("sensor.outdoor_temp_and_humidity_temperature") < states("sensor.lr_temperature") -%}
        Cooler Outside
      {%- else -%}
        Warmer Outside
      {%- endif %}

```
```
# This Sensor is dead simple numeric value (float) if warmer or cooler outside
platform: template
sensors:
  warmer_or_cooler_outside_value:
    friendly_name: 'Warmer or Cooler Outside Value'
    value_template: >
      {{states.sensor.outdoor_temp_and_humidity_temperature.state | float - states.sensor.lr_temperature.state | float }}
```
